#! /bin/sh
# From The elasticsearch Book
# The original of this file can be found at: http://elasticsearchbook.com/code/index.html
#
#
# elasticsearch Start/Stop elasticsearch
#
# chkconfig: 345 99 99
# description: elasticsearch
# processname: elasticsearch

name="elasticsearch"
runuser="elk"
elasticsearch_home="/opt/elasticsearch"
elasticsearch_log="$elasticsearch_home/elasticsearch.log"

find_elasticsearch_process () {
    PIDTEMP=`ps aux | grep elasticsearch | grep java | awk '{ print $2 }'`
    # Pid not found
    if [ "x$PIDTEMP" = "x" ]; then
        PID=-1
    else
        PID=$PIDTEMP
    fi
}

start () {
    LOG_DIR=`dirname ${elasticsearch_log}`
    if [ ! -d $LOG_DIR ]; then
      echo "Log dir ${LOG_DIR} doesn't exist. Creating"
      mkdir $LOG_DIR
    fi
    su $runuser -c "cd ${elasticsearch_home} && bin/elasticsearch -d"
}

stop () {
    find_elasticsearch_process
    if [ $PID -ne -1 ]; then
        kill -9 $PID
    fi
}

case $1 in
start)
        start
        ;;
stop)
        stop
        exit 0
        ;;
reload)
        stop
        sleep 2
        start
        ;;
restart)
        stop
        sleep 2
        start
        ;;
status)
        find_elasticsearch_process
        if [ $PID -gt 0 ]; then
          echo "elasticsearch running: $PID"
          exit 0
        else
          echo "elasticsearch not running"
          exit 1
        fi
        ;;
*)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        RETVAL=1
esac
exit 0

