global:
  resolve_timeout: 1m
  smtp_smarthost: 'mail.example.com:25'
  smtp_from: "useradmin@example.com"
  smtp_auth_username: "useradmin@example.com"
  smtp_auth_password: 'for-your-password'
  smtp_require_tls: false

route:
  group_by: ['alertname']
  group_wait: 5s
  group_interval: 1m
  repeat_interval: 3h
  receiver: 'email'

  routes:
  - match:
      severity: warning
    receiver: 'email'
    continue: true

  - match:
      severity: warning
    receiver: 'slack_general'

receivers:
- name: 'slack_general'
  slack_configs:
  - api_url: 'http://10.100.14.41:8065/hooks/98s1md9yc7bnzdb493j73thiqc'
    send_resolved: true
    text: "{{ range .Alerts }}{{ .Labels.job }} {{ end }}\n{{ range .CommonAnnotations.SortedPairs }}{{ .Name }} = {{ .Value }}\n{{ end }}"

- name: 'email'
  email_configs:
  - to: "973426729@qq.com"
    send_resolved: true
